topic: "Ma olen viinapuu"
chapter: "John 15:2-8"
couplet_verse_numbers: "2-8"
couplet_verses_text: |
  Iga viljatu oksa lõikab ta minu küljest ära. Iga viljakandvat oksa ta puhastab, et see kannaks veel enam vilja. Teie olete juba puhtad õpetuse tõttu, mille ma olen teile andnud. 
  Jääge minusse, ja mina jään teisse. Nagu oks ei saa kanda vilja omaette; ta peab jääma viinapuu külge. Nii ka teie ei kanna vilja, kui te ei jää minusse.
  Mina olen viinapuu, teie olete oksad. Kes jääb minusse ja mina temasse, see kannab palju vilja, sest minust lahus ei saa te midagi teha. Kes ei jää minusse, on nagu äravisatud oks - ta kuivab. Need korjatakse kokku, visatakse tulle ja põletatakse ära. 
  Kui te jääte minusse ja minu sõnad jäävad teisse, siis paluge, mida te iganes soovite, ja see sünnib teile. 8See toob au minu Isale, kui te kannate palju vilja näidates, et te olete minu jüngrid.

chorus_verse_numbers: "1, 9"
chorus_verses_text: "Mina olen tõeline viinapuu ja minu Isa on aednik. Nõnda nagu Isa on armastanud mind, olen mina armastanud teid. Jääge minu armastusse!"

output_filename: "ma_olen_viinapuu"
