topic: "Meie Isa Palve"
chapter: "Matthew 6:9-13"
couplet_verse_numbers: "9-13"
couplet_verses_text: |
  Palvetage siis nõnda: Meie Isa, kes sa oled taevas! Pühitsetud olgu sinu nimi!
  Sinu riik tulgu, sinu tahtmine sündigu nagu taevas, nõnda ka maa peal!
  Meie igapäevast leiba anna meile tänapäev!
  Ja anna meile andeks meie võlad, nagu meiegi andeks anname oma võlglastele!
  Ja ära saada meid kiusatusse, vaid päästa meid ära kurjast!
  Sest sinu päralt on riik ja vägi ja au igavesti. Aamen.

chorus_verse_numbers: "6"
chorus_verses_text: "palveta oma Isa poole salajas. Ja sinu Isa, kes näeb salajasse, tasub sulle"

output_filename: "meie_isa_palve_iii"
